name: Magic light video

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL to test'
        required: true
        default: 'https://invideo.io/'
      prompt:
        description: "Enter the prompt"
        required: true
        default: "Enter a prompt for the Video "
      message:
        description: "Enter the message for the comments"
        required: true
        default: "https://wellmedic.in"

jobs:
  ui-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Selenium Test
        env:
          URL_TO_TEST: ${{ github.event.inputs.url }}
          PROMPT: ${{ github.event.inputs.prompt }}
          MESSAGE: ${{ github.event.inputs.message }}
        run: python app.py "$env:URL_TO_TEST" "$env:PROMPT" "$env:MESSAGE"
        shell: powershell
