name: Selenium UI Automation (Python)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL to test'
        required: true
        default: 'https://invideo.io/'
      prompt:
        description: 'Enter the prompt'
        required: true
        default: 'Enter a prompt for the Video'
      message:
        description: 'Enter the message for the comments'
        required: true
        default: 'https://wellmedic.in'

jobs:
  ui-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Google Chrome (via Chocolatey)
        shell: powershell
        run: |
          choco install googlechrome --no-progress --yes

      - name: Install matching ChromeDriver
        shell: powershell
        run: |
          $chromeVersion = (& "C:\Program Files\Google\Chrome\Application\chrome.exe" --version).Split()[2]
          $major = $chromeVersion.Split('.')[0]
          $jsonUrl = "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"
          $json = Invoke-RestMethod $jsonUrl
          $match = $json.versions | Where-Object { $_.version -like "$major.*" } | Select-Object -First 1
          $driverUrl = $match.downloads.chromedriver | Where-Object { $_.platform -eq "win64" } | Select-Object -ExpandProperty url
          $zipPath = "$env:TEMP\chromedriver.zip"
          Invoke-WebRequest $driverUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath "C:\tools\chromedriver" -Force
          echo "C:\tools\chromedriver\chromedriver-win64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify Chrome and ChromeDriver versions
        shell: powershell
        run: |
          & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium Test
        env:
          URL_TO_TEST: ${{ github.event.inputs.url }}
          PROMPT: ${{ github.event.inputs.prompt }}
          MESSAGE: ${{ github.event.inputs.message }}
        shell: powershell
        run: python app.py "$env:URL_TO_TEST" "$env:PROMPT" "$env:MESSAGE"
