name: Selenium UI Automation (Python)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL to test'
        required: true
        default: 'https://invideo.io/'

jobs:
  ui-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download and Install Google Chrome
        run: |
          $ChromeInstaller = "$env:TEMP\chrome_installer.exe"
          Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile $ChromeInstaller
          Start-Process -FilePath $ChromeInstaller -Args "/silent /install" -Wait
        shell: powershell

      - name: Add Chrome to PATH
        run: |
          echo "C:\Program Files\Google\Chrome\Application" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Selenium Test
        env:
          URL_TO_TEST: ${{ github.event.inputs.url }}
        run: python app.py "$env:URL_TO_TEST"
        shell: powershell
