name: Selenium UI Automation (Python)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL to test'
        required: true
        default: 'https://invideo.io/'

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "✅ Chrome and Chromedriver installed"

      - name: Verify Chrome installation
        run: |
          if command -v chromium-browser > /dev/null; then
            echo "✅ Chromium found at: $(which chromium-browser)"
            chromium-browser --version
          else
            echo "❌ Chromium not found!" && exit 1
          fi

          if command -v chromedriver > /dev/null; then
            echo "✅ Chromedriver found at: $(which chromedriver)"
            chromedriver --version
          else
            echo "❌ Chromedriver not found!" && exit 1
          fi

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Selenium Test
        env:
          URL_TO_TEST: ${{ github.event.inputs.url }}
        run: python app.py "$URL_TO_TEST"
