name: Selenium UI Automation (Python)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL to test'
        required: true
        default: 'https://invideo.io/'

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install -r requirements.txt

      - name: Run Selenium Test
        env:
          URL_TO_TEST: ${{ github.event.inputs.url }}
        run: python app.py "$URL_TO_TEST"
